language: node_js
node_js:
- node
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export newPkgVersion=`node -p "require('./package.json').version"`
- export oldPublishedVersion=`npm view ngx-codetab version`
before_script:
- npm i -g --silent @angular/cli
script:
- npm run build:prod
before_deploy:
- git tag "1.0.0";
deploy:
- provider: releases
  api_key:
    secure: WyF6WAqlpWla7plG5BpE1jnQWJpG6o4gVhfKNS4Zl9VZ433GHCmde1gM4+G9OtgKyNNNN7U7rnKVEOgzW7CVDS5YoxwKhMVhZlKRZdj62GU2st/s3XlORcgZgrYo+1c7xxs/YW4y2o//VdprfCwGvStE2xo5R6c9gru8F5kYjfPr/xvB70FHw+KZJ0qdMbycw3umM/qAKJIDtmAjZ+/UUmLkgiJuzQiAe5355XLI6PsRVOkGu4jJYSFhI6Zz1qRaX7Iq0UQORFX9uXdx6URFjOU7Z3gt/Z/7o9v7yWbohSEfMTX1YyvE5nw9KVLom9ze1R6zmiC4p8ZvDiRWBD6RT6Ag6vQXtyMyuRUpjOX0WGLpzsJFWOER9rvuNXTheAdRTP4RkWPIPUlmbyhseyPJmUDobJ6KtF9rJZe6e8e3NqIGHvlQeytVf5+v0GdOve7h4tVMrDFRt0jKnxQUHdagIPuO6cU3vRiVRXKLWZCCVsIxIkP9elLYP583hyx8PgBGRCsD2maQ3lWBp5GP+oxeueP3Wg4uGVY+DKJS7LoFYe9wnTOu6TFC9YjZdwqiL8R+RKMrdbCU7NVc04miNBBI46pZGuKSBwTyKw9RN8BQO5QpUuA3hRo4EtpxphQ187Zsobnc3yP5mFx6jNgcVlI3KT5RTFfaGXwlaixG+4uekIQ=
  file: "/dist/ngx-codetab"
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: change

