language: node_js
node_js:
- node
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export newPkgVersion=`node -p "require('./package.json').version"`
- export oldPublishedVersion=`npm view ngx-codetab version`
before_script:
- npm i -g --silent @angular/cli
script:
- npm run build:prod
before_deploy:
- git tag "1.0.0";
deploy:
- provider: releases
  api_key:
    secure: dKNJ/xjJAurfwwEeA5lhEoHxU3QY+M8atq86uPq2b56GkDTiWz7Qed4qcx9FdHxjDR6ctQ6RfI4LOWEo1wFnB032L2HoBRszXXQMTUGBZdt+3MmClpbiWqFiKbmbjD3jt2X9R6rQKyF2xM9vRnPmfXdFyiseOzTm0h3zHPQcujNU4Nihdu7xEYLm7rEySZcuUm4mg6EftwtZ1DVn3jzTmx2eNL0MrOnogyNmZfEhlw/TecIuCdCCGTjhAXQoeErOYRybywT/3HmRnIJrQgUot8ORFsLYy9Dfrc3+fpYrphVV59NmduT5Q2eQ6tm/6+0IOQzgmmgKLv6yMgsmd9/oT7vL9RJw8DWCTFe1mnrupWOw0wDz05vMwRz/lkXAsR7oHLh1xCg7j7Uir7amY662GzfaCr746EVxF/b3IPLKHq4uIeEyywIamJEx1J36uq+8dG3vZwljS410kBmBwdwMpvCCWYK48mh0IOepf6E4sNp3LohQ0iUIEyxLQ1ZELHbAygOHbmuHpjBubBkHICmElTJuq+saOFcFi2ZP4G6Rml2mfzXUy5uGWUI2uta8iXmoc6HKcEhRTRSv90+TmT4x3xiG8qkcTBypJesyHRXNo3CEVZDcIdNBPP6cm8pL3deV5xC5TCdTlXe1BqRSk+YrvaDeqlnWzqs5iTx2cdZdhY0=
  file: "/dist/ngx-codetab"
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: change
