language: node_js
node_js:
 - node
before_install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - export newPkgVersion=`node -p "require('./package.json').version"`
 - export oldPublishedVersion=`npm view ngx-codetab version`
before_script:
 - npm i -g --silent @angular/cli
script:
 - npm run build:prod
before_deploy:
 - git tag "${newPkgVersion}";
deploy:
  - provider: releases
    api_key:
        secure: a0KM16TDR9tGBYQmbDqsVG6MOW5+VsyDSvrvDeMOXWlL8ZJoplDizZFucNvwHpycu4iNvkqcwJhtx5Tf9Wj3lofKJlLDrB664s/G1kX2ywAGj9TGIyNRCPpa+WGS9oGqZOhFY5IPEm1iCrqquHTovaPtg9o4oxkhKgkN0ZQsooYZ3LoR7glT6yy1jXH/jfcWnClktfPyjEh7cXXJeKmmJCrDcre1NkIwDuaAy9D8NOZRbwQsPDqyD5yWSYmICcN6XG0D7u7KSYPTJs+R9t2HOv20Av0aR3/xU/W1atWM+INFrJVSZKyKfoAh2A3YGdsrnLny45w+tS4vbDTw2lEVEl9B6shsxr3DVhz+x/7RCe/FhfwZw1igJE2N3HtywOwMT1kf7N0RRPE9/Yk9GKnVo1Pc/fjaI13wlsgn9rhE1YRvoNTCqQQqK1oUtGqkf4nAJ0dnM9/ayQ3A9IYvo0LHN/DdKsHPncS8wV5+aiXHKYGJ8oQMSl8eos0n+hMMKA4i07VfhmDQK3cEG67xeYH8OACxzqRsBTx69dFuNp7aiFGYI+mPZJ/KKf0m09kvdHO9bYkNr2vZU184QUCxCHdIxLp9GmcC9z1kFqo/6oHCcW4l0R1oLdimKt/Y9VDDUcQjjMjPg1o8b27zH5kgN+ZMX71VWwV5Yy5dihYdbxwellQ=
    file: "/dist/ngx-codetab"
    skip_cleanup: true
    on:
        branch: master
notifications:
    email:
        on_success: never
        on_failure: change
